CREATE DATABASE ALEGERI
GO
USE ALEGERI
GO
CREATE TABLE SECTII (
ID INT PRIMARY KEY IDENTITY (1,1),
NUMAR INT
)

CREATE TABLE CETATENI (
ID INT PRIMARY KEY IDENTITY (1,1),
NUME VARCHAR(100),
PRENUME VARCHAR(100),
CNP VARCHAR(20),
ID_SECTIE_VOTARE INT FOREIGN KEY REFERENCES SECTII(ID)
)

CREATE TABLE VOTURI(
ID INT PRIMARY KEY IDENTITY (1,1),
ORA TIME,
PE_LISTE_SUPLIMENTARE BIT,
ID_CETATEAN INT FOREIGN KEY REFERENCES CETATENI(ID),
ID_SECTIE_VOTARE INT FOREIGN KEY REFERENCES SECTII(ID),
)

CREATE TABLE FIRME_CATERING (
ID INT PRIMARY KEY IDENTITY (1,1),
NUME VARCHAR(100),
CIF VARCHAR(100)
)

CREATE TABLE SECTII_CATERING (
ID INT PRIMARY KEY IDENTITY(1,1),
ID_SECTIE_VOTARE INT FOREIGN KEY REFERENCES SECTII(ID),
ID_CATERING INT FOREIGN KEY REFERENCES FIRME_CATERING(ID)
)

GO

CREATE OR ALTER PROCEDURE USP_EXPRIMARE_VOT (@ID_CETATEAN INT, @ID_SECTIE_VOTARE INT)
AS
	DECLARE @NUME_CETATEAN VARCHAR(100)
	DECLARE @PRENUME_CETATEAN VARCHAR(100)
	IF EXISTS (SELECT * FROM VOTURI WHERE ID_CETATEAN = @ID_CETATEAN)
	BEGIN
		SELECT @NUME_CETATEAN = NUME, @PRENUME_CETATEAN = PRENUME FROM CETATENI WHERE ID = @ID_CETATEAN
		PRINT N'CETATEANUL' + @NUME_CETATEAN + ' ' + @PRENUME_CETATEAN + ' A VOTAT DEJA'
		RETURN 1
	END

	DECLARE @PE_LISTE_SUPLIMENTARE BIT
	SELECT @PE_LISTE_SUPLIMENTARE = 1 FROM CETATENI
	WHERE ID = @ID_CETATEAN
	AND ID_SECTIE_VOTARE <> @ID_SECTIE_VOTARE

	INSERT INTO VOTURI(ORA, PE_LISTE_SUPLIMENTARE, ID_CETATEAN, ID_SECTIE_VOTARE) VALUES
	(GETDATE(), @PE_LISTE_SUPLIMENTARE, @ID_CETATEAN, @ID_SECTIE_VOTARE)
GO

CREATE OR ALTER VIEW VW_NR_VOTURI AS 
SELECT '12-13' AS [ORA], COUNT(*) AS [NUMAR DE VOTURI] 
FROM VOTURI 
WHERE DATEPART(HOUR, ORA) BETWEEN 12 AND 13
UNION
SELECT '13-14' AS [ORA], COUNT(*) AS [NUMAR DE VOTURI] 
FROM VOTURI 
WHERE DATEPART(HOUR, ORA) BETWEEN 13 AND 14
UNION
SELECT '14-15' AS [ORA], COUNT(*) AS [NUMAR DE VOTURI] 
FROM VOTURI 
WHERE DATEPART(HOUR, ORA) BETWEEN 14 AND 15

GO
INSERT INTO SECTII (NUMAR) VALUES 
(1), (2), (3)

INSERT INTO CETATENI (ID_SECTIE_VOTARE) VALUES
(1), (1), (1),
(2), (2), (2),
(3), (3), (3)

GO


DECLARE	@return_value int

EXEC	@return_value = [dbo].[USP_EXPRIMARE_VOT]
		@ID_CETATEAN = 1,
		@ID_SECTIE_VOTARE = 2

GO

SELECT * FROM VW_NR_VOTURI