CREATE DATABASE Caleidoscop
go
USE Caleidoscop
go
CREATE TABLE EPISOADE (
ID INT PRIMARY KEY IDENTITY(1,1),
DURATA INT, -- SECUNDE
NUME VARCHAR(50),
ORDINE_CRONOLOGICA INT
)

CREATE TABLE UTILIZATORI (
ID INT PRIMARY KEY IDENTITY (1,1),
NUME VARCHAR(50),
EMAIL VARCHAR(50)
)

CREATE TABLE VIZIONARI (
ID_UTILIZATOR INT FOREIGN KEY REFERENCES UTILIZATORI(ID),
ID_EPISOD INT FOREIGN KEY REFERENCES EPISOADE(ID)
CONSTRAINT PK_VIZIONARI PRIMARY KEY (ID_UTILIZATOR, ID_EPISOD)
)

CREATE TABLE ACTORI (
ID INT PRIMARY KEY iDENTITY (1,1),
NUME VARCHAR(50)
)

CREATE TABLE REPLICI (
ID INT PRIMARY KEY IDENTITY (1,1),
TEXT VARCHAR(50),
TIMP_REPLICA INT, --SECUNDA IN EPISOD CAND E SPUSA
ID_ACTOR INT FOREIGN KEY REFERENCES ACTORI(ID),
ID_EPISOD INT FOREIGN KEY REFERENCES EPISOADE(ID)
)

/*
AVEM NEVOIE DE ACEST TABEL PENTRU CA UN ACTOR POATE
SA NU AIBA REPLICI INTR-UN EPISOD SI TOTUSI APARE IN EL
*/
CREATE TABLE ACTORI_EPISOADE (
ID_ACTOR INT FOREIGN KEY REFERENCES ACTORI(ID),
ID_EPISOD INT FOREIGN KEY REFERENCES EPISOADE(ID),
CONSTRAINT PK_ACTORI_EPISOADE PRIMARY KEY (ID_ACTOR, ID_EPISOD)
)

GO

CREATE OR ALTER PROCEDURE PLAY (@ID_UTILIZATOR INT) 
AS
	DECLARE @NR_EPISOADE_VIZIONATE INT
	SELECT @NR_EPISOADE_VIZIONATE = COUNT(*) FROM VIZIONARI
	WHERE ID_UTILIZATOR = @ID_UTILIZATOR
	
	IF @NR_EPISOADE_VIZIONATE = 9
		RETURN
	IF @NR_EPISOADE_VIZIONATE = 8
	BEGIN
		INSERT INTO VIZIONARI VALUES (@ID_UTILIZATOR, 9)
		RETURN
	END
	DECLARE @URMATORUL_EPISOD INT
	SET @URMATORUL_EPISOD = FLOOR(1 + RAND() * 8) -- genereaza un int in [1,8] 
	WHILE @URMATORUL_EPISOD <> 9 and 
		  EXISTS (SELECT 1 FROM VIZIONARI VIZ
				  INNER JOIN EPISOADE EPI ON VIZ.ID_EPISOD = EPI.ID
				  WHERE VIZ.ID_UTILIZATOR = @ID_UTILIZATOR
					AND EPI.ORDINE_CRONOLOGICA = @URMATORUL_EPISOD)
		SET @URMATORUL_EPISOD = FLOOR(1 + RAND() * 8)

	DECLARE @ID_URMATORUL_EPISOD INT
	SELECT @ID_URMATORUL_EPISOD = ID FROM EPISOADE WHERE ORDINE_CRONOLOGICA = @URMATORUL_EPISOD

	INSERT INTO VIZIONARI VALUES (@ID_UTILIZATOR, @ID_URMATORUL_EPISOD)

GO
INSERT INTO UTILIZATORI (NUME, EMAIL) VALUES 
('BOGDANEL_BD', 'BOGDANEL_BD@BDRULZ.COM'),
('DONALD', 'DDONALD@US.COM')

INSERT INTO ACTORI (NUME) VALUES
('PAZ VEGA'), ('TATI GABRIELLE'), ('GIANCARLO ESPOSITO')

INSERT INTO EPISOADE (DURATA, NUME, ORDINE_CRONOLOGICA) VALUES 
(25, 'BLACK', 1), (30, 'YELLOW', 2), (25, 'GREEN', 3), (30, 'BLUE', 4),
(25, 'ORANGE', 5), (30, 'VIOLET', 6), (25, 'RED', 7), (30, 'PINK', 8),
(40, 'WHITE: THE HEIST', 9)

INSERT INTO REPLICI (TEXT, TIMP_REPLICA, ID_ACTOR, ID_EPISOD) VALUES
('BUNA SEARA, STUDENT', 20, 3, 1),
('BUNA SEARA, DOMN PROFESOR', 1, 1, 1),
('5', 5, 3, 9),
('CE NOTA AM LA BAZE DE DATE?', 4, 1, 7),
('MULTUMESC!', 21, 1, 6)

SELECT ACT.NUME + ': ' + REP.TEXT AS SCRIPT FROM ACTORI ACT
INNER JOIN REPLICI REP ON REP.ID_ACTOR = ACT.ID
INNER JOIN EPISOADE EPI ON EPI.ID = REP.ID_EPISOD
ORDER BY EPI.ORDINE_CRONOLOGICA, REP.TIMP_REPLICA

GO

DECLARE @ID_UTILIZATOR INT = 1
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR

SET @ID_UTILIZATOR = 2
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR
EXECUTE [dbo].[PLAY] @ID_UTILIZATOR

SELECT * FROM VIZIONARI
