CREATE DATABASE CAMPIONAT_DE_TABLE
GO

USE CAMPIONAT_DE_TABLE
GO

CREATE TABLE ANGAJATI (
ID INT PRIMARY KEY IDENTITY(1,1),
NUME VARCHAR(50),
NR_CONTRACT VARCHAR(10)
)

CREATE TABLE MESE (
ID INT PRIMARY KEY IDENTITY(1,1),
NUMAR INT,
CULOARE VARCHAR(50)
)

CREATE TABLE MECIURI (
ID INT PRIMARY KEY IDENTITY(1,1),
DATA_MECI DATE,
ID_PART_1 INT FOREIGN KEY REFERENCES ANGAJATI(ID),
ID_PART_2 INT FOREIGN KEY REFERENCES ANGAJATI(ID),
ID_CASTIGATOR INT FOREIGN KEY REFERENCES ANGAJATI(ID)
)

CREATE TABLE MUTARI (
ID INT PRIMARY KEY IDENTITY(1,1),
ID_JUCATOR INT FOREIGN KEY REFERENCES ANGAJATI(ID),
ID_MECI INT FOREIGN KEY REFERENCES MECIURI(ID),
ZAR_1 INT,
ZAR_2 INT,
PIESA_MUTATA_DE_LA VARCHAR(10),
PIESA_MUTATA_LA VARCHAR(10)
)

/*
ID-UL SPECTATORULUI E DIFERIT DE ID-UL PARTICIPANTILOR PT ACEL MECI
*/
CREATE TABLE SPECTATORI(
ID_SPECTATOR INT FOREIGN KEY REFERENCES ANGAJATI(ID),
ID_MECI INT FOREIGN KEY REFERENCES MECIURI(ID),
CONSTRAINT PK_SPECTATORI PRIMARY KEY (ID_SPECTATOR, ID_MECI)
)

GO

CREATE OR ALTER PROCEDURE USP_PREMIU (@ID_PARTICIPANT INT)
AS
	DECLARE @NR_MECIURI_CASTIGATE INT
	SELECT @NR_MECIURI_CASTIGATE = COUNT(*) 
	FROM MECIURI 
	WHERE ID_CASTIGATOR = @ID_PARTICIPANT

	DECLARE @NR_SPECTATORI INT
	SELECT @NR_SPECTATORI = COUNT(*) 
	FROM SPECTATORI SP 
	INNER JOIN MECIURI ME ON SP.ID_MECI = ME.ID
	WHERE @ID_PARTICIPANT IN (ME.ID_PART_1, ME.ID_PART_2)

	-- DACA A JUCAT, L-A VAZUT
	-- MECIURI NE VAZUTE = TOTAL_MECIURI - MECIURI VAZUTE
	-- MECIURI VAZUTE = MECIURI PARTICIPANT + MECIURI SPECTATOR
	DECLARE @NR_MECIURI_PARTICIPANT INT
	SELECT @NR_MECIURI_PARTICIPANT = COUNT(*) 
	FROM MECIURI 
	WHERE @ID_PARTICIPANT IN (ID_PART_1, ID_PART_2)

	DECLARE @NR_MECIURI_SPECTATOR INT
	SELECT @NR_MECIURI_SPECTATOR = COUNT(*) 
	FROM SPECTATORI 
	WHERE ID_SPECTATOR = @ID_PARTICIPANT

	DECLARE @TOTAL_MECIURI INT
	SELECT @TOTAL_MECIURI = COUNT(*) 
	FROM MECIURI

	DECLARE @PREMIU INT
	SET @PREMIU = @NR_MECIURI_CASTIGATE * 100 
				+ @NR_SPECTATORI * 10 
				+ (@TOTAL_MECIURI - (@NR_MECIURI_PARTICIPANT + @NR_MECIURI_SPECTATOR)) * (-10)

	IF @PREMIU < 0
		RETURN 0
	RETURN @PREMIU

GO

CREATE OR ALTER VIEW VW_DUBLE AS
SELECT COUNT(*) AS NR_DUBLE FROM ANGAJATI AN 
INNER JOIN MUTARI MU ON AN.ID = MU.ID_JUCATOR
WHERE AN.NR_CONTRACT LIKE 'CLF3215' AND MU.ZAR_1 = MU.ZAR_2

GO

INSERT INTO ANGAJATI (NUME, NR_CONTRACT) VALUES
('BOGDAN IOAN', 'CLF3215'),
('IOAN URSU', 'CLF2254'),
('NICOLAE IORGA', 'CLF2134'),
('AXENTE SEVER', 'CLF0023'),
('EMIL RACOVITA', 'CLF0213')

INSERT INTO MECIURI (DATA_MECI, ID_PART_1, ID_PART_2, ID_CASTIGATOR) VALUES
(GETDATE(), 1,2, 1),
(GETDATE(), 1,3, 1),
(GETDATE(), 1,4, 1),
(GETDATE(), 1,5, 5),
(GETDATE(), 2,3, 2)

INSERT INTO SPECTATORI (ID_MECI, ID_SPECTATOR) VALUES
(1, 3), (1,4), (1,5),
(2,2), (2,5),
(3,2), (3,3), (3,5),
(4,2), (4,3), (4,4)

INSERT INTO MUTARI (ID_JUCATOR, ID_MECI, ZAR_1, ZAR_2, PIESA_MUTATA_DE_LA, PIESA_MUTATA_LA) VALUES
(1,1,5,5, '1-2', '2-3'),
(2,1,5,5, '1-2', '2-3'),
(1,2,4,4, '1-2', '2-3'),
(3,5,5,5, '1-2', '2-3'),
(1,3,3,4, '1-2', '2-3')

GO
DECLARE @PREMIU INT
EXECUTE @PREMIU = USP_PREMIU 1
SELECT @PREMIU
-- 400. 3 MECIURI CASTIGATE, 11 SPECTATORI, 1 MECI NEVAZUT

GO
SELECT * FROM VW_DUBLE